# Generated by Django 5.0.6 on 2024-05-12 09:43

import django.db.models.deletion
import reservations_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_seats', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_t', models.TimeField()),
                ('end_t', models.TimeField()),
                ('date', models.DateField(validators=[reservations_app.models.validate_date])),
                ('seats_needed', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations_app.table')),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
    ]
