# Generated by Django 5.0.6 on 2024-05-15 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='time',
            new_name='start_time',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='duration',
        ),
    ]
